# Generated by Django 2.2.17 on 2023-07-25 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackethon_app', '0002_hackethon_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackethon',
            name='username',
        ),
    ]
