# Generated by Django 2.2.17 on 2023-07-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackethon_app', '0003_remove_hackethon_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackethon',
            name='background_image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='hackethon',
            name='hackethon_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
