# Generated by Django 2.2.17 on 2023-07-25 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hackethon_app', '0004_auto_20230725_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackethon',
            name='username',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hackethon',
            name='background_image',
            field=models.ImageField(upload_to='static/'),
        ),
        migrations.AlterField(
            model_name='hackethon',
            name='hackethon_image',
            field=models.ImageField(upload_to='static/'),
        ),
    ]
