# Generated by Django 2.2.17 on 2023-07-26 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hackethon_app', '0005_auto_20230725_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackethonsubmission',
            name='username',
        ),
        migrations.AlterField(
            model_name='hackethonsubmission',
            name='hackethon_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackethon_app.HackethonRegistration'),
        ),
    ]
