# Generated by Django 2.2.17 on 2023-07-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackethon_app', '0006_auto_20230726_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackethon',
            name='prize',
            field=models.CharField(default='$500', max_length=10),
        ),
    ]
